version: '3.8'
services:
  postgres:
    image: postgres:16.8
    container_name: user_service_db
    environment:
      - POSTGRES_USER=user_service
      - POSTGRES_PASSWORD=user_service
      - POSTGRES_DB=user_service
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local